version: "3"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env.docker
    restart: always
    volumes:
      - ./server:/app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    networks:
      - sales-dash-network
    container_name: sales-dash-server

  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    env_file:
      - ./app/.env
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    restart: always
    networks:
      - sales-dash-network
    container_name: sales-dash-app

  mongo:
    image: mongo:latest
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - sales-dash-network
    container_name: sales-dash-mongo

networks:
  sales-dash-network:
    driver: bridge
