info:
  contact: {}
paths:
  /api/dashboard:
    get:
      description: Retrieve sales data for the dashboard
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved sales dashboard
          schema:
            type: object
      summary: Get dashboard sales data
  /api/product:
    get:
      description: Retrieve all products data
      parameters:
      - description: Limit number of products per page
        in: query
        name: limit
        type: integer
      - description: Offset for pagination
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved products
          schema:
            type: object
        "500":
          description: Internal Server Error
          schema:
            type: object
      summary: Get all products
  /api/sale:
    get:
      description: Retrieve all sales data
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved sales
          schema:
            type: object
      summary: Get all sales
  /api/sale-brand:
    get:
      description: Retrieve sales data grouped by brand
      parameters:
      - description: Items per page
        in: query
        name: perPage
        type: integer
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Field to sort by
        in: query
        name: sortBy
        type: string
      - description: Sort order (asc/desc)
        in: query
        name: sortOrder
        type: integer
      - description: Text to search
        in: query
        name: searchText
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved sales by brand
          schema:
            type: object
      summary: Get sales by brand
  /api/sale-product:
    get:
      description: Retrieve sales data grouped by product
      parameters:
      - description: Items per page
        in: query
        name: perPage
        type: integer
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Field to sort by
        in: query
        name: sortBy
        type: string
      - description: Sort order (asc/desc)
        in: query
        name: sortOrder
        type: integer
      - description: Text to search
        in: query
        name: searchText
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved sales by product
          schema:
            type: object
      summary: Get sales by product
  /new-file-notification:
    get:
      description: Initiates a connection for Server-Sent Events (SSE) with the client
      produces:
      - text/plain
      responses: {}
      summary: Establish a Server-Sent Events (SSE) connection
swagger: "2.0"
